apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
      
permissions:
  id-token: read
  
jobs:
  build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Hello
        uses: docker://golang:1.22.4
        shell: sh
        run: |
          echo "hello world"
      - name: Build
        uses: docker://golang:1.22.4
        shell: sh
        run: |
          cd hello; go build; ls;
      - id: testAction
        name: Test publish-evidence-item action
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## Test markup and property rendering
            - Run ID: ${{ cloudbees.run_id }}
            ## some tags are removed for security, so span wont work
            - User values: user-defined text and markup could go here


