apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Hello
        uses: docker://golang:1.21.6
        shell: sh
        run: |
          echo "hello world"
      - name: Build
        uses: docker://golang:1.21.6
        shell: sh
        run: |
          cd hello; go build; ls;


