apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  schedule:
    - cron: 0,10,20,30,40,50 * * * *

permissions:
  id-token: read|write
jobs:
  build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Hello
        uses: docker://golang:1.22.4
        shell: sh
        run: |
          echo "hello world"
      - name: Build
        uses: docker://golang:1.22.4
        shell: sh
        run: |
          cd hello; go build; ls;
      - id: testAction
        name: Test publish-evidence-item action
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## Comments are titles for the content
            - User values: user-defined text and markup could go here
            ## Supported fields can be listed
            - Run ID: ${{ cloudbees.run_id }}
            - Version: ${{ cloudbees.version }}
            ## SCM
            - Branch: ${{ cloudbees.scm.branch}}
            - SHA: ${{ cloudbees.scm.sha }}
    needs:
      - FinishTheThing
  FinishTheThing:
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 56948ada-7876-11ec-be47-42010a83ae75
      disallowLaunchByUser: false
      instruction: Approve this please.
